# Generated by Django 2.2.1 on 2019-05-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
